# Uncomment the next line to define a global platform for your project
platform :osx, '10.10'

target 'FKApnsMac' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'KVOController', '~> 1.2.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'Mantle', '~> 2.1.0'
  pod 'JWT', '~> 3.0.0-beta.11'
  pod 'pop', '~> 1.0.10'

end
